# This is a basic workflow to help you get started with Actions
name: add Label
on:
  issues:
    types:
      - reopened
      - opened
jobs:          
  add_label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: 
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.testToken }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: enhancement
